RCS ON.

LOCK THROTTLE TO 0.3.
WAIT 0.2.

// Launch
STAGE.
WAIT 1.2.

// Initiate turn
SET SHIP:CONTROL:PITCH TO -1.0.
WAIT 0.4.       // RCS burn
SET SHIP:CONTROL:PITCH TO 0.0.
WAIT 0.35.       // Turning...
// End turn
SET SHIP:CONTROL:PITCH TO 1.0.
WAIT 0.4.       // RCS burn
SET SHIP:CONTROL:PITCH TO 0.0.

SET Y TO HEADING(0, 0).
LOCK STEERING TO Y.
RCS OFF.
LOCK THROTTLE TO 1.0.

WAIT 60.